name: sgpa-in-sr
channels:
  - defaults
dependencies:
  - pip=24.2
  - python=3.12.7
  - setuptools=75.1.0
  - pip:
      - matplotlib==3.9.3
      - multiprocess==0.70.17
      - numpy==2.0.2
      - pandas==2.2.3
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - shap==0.46.0
      - sympy==1.13.3
